server:
  port: 8111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    api:
      path: /client/**
      url: http://localhost:8100/
    admin:
      path: /admin/**
      url: http://localhost:9090/applications
